// Muscle names and app muscle groups for the anatomy model's nodes.
//
// Nodes in public/models/muscles.glb are named `ta2-<id>.<side>` (Terminologia
// Anatomica 2). English names come from Wikidata (property P7173, CC0). The
// group decides body-map colour and which exercises a click shows; null means
// the muscle is shown and named on hover but isn't tracked by the app.
// Generated once; edit by hand if a grouping should change.

import type { MuscleGroup } from '@/types/db'

export const TA2_MUSCLES: Record<string, [name: string, group: MuscleGroup | null]> = {
  '2042': ['Superior rectus muscle', null],
  '2043': ['Inferior rectus muscle', null],
  '2044': ['Medial rectus muscle', null],
  '2045': ['Lateral rectus muscle', null],
  '2047': ['Anulus tendineus communis', null],
  '2048': ['Superior oblique muscle', null],
  '2049': ['Trochlea of superior oblique', null],
  '2051': ['Inferior oblique muscle', null],
  '2052': ['Levator palpebrae superioris muscle', null],
  '2056': ['Frontalis muscle', null],
  '2057': ['Occipitalis muscle', null],
  '2058': ['Temporoparietalis muscle', null],
  '2059': ['Galea aponeurotica', null],
  '2061': ['Procerus muscle', null],
  '2062': ['Nasalis muscle', null],
  '2065': ['Depressor septi nasi muscle', null],
  '2067': ['Palpebral part of orbicularis oculi', null],
  '2070': ['Orbital part of orbicularis oculi', null],
  '2071': ['Corrugator supercilii muscle', null],
  '2072': ['Depressor supercilii muscle', null],
  '2073': ['Orbicularis oris muscle', null],
  '2076': ['Depressor anguli oris muscle', null],
  '2077': ['Transverse muscle of the chin', null],
  '2078': ['Risorius muscle', null],
  '2079': ['Zygomaticus major muscle', null],
  '2080': ['Zygomaticus minor muscle', null],
  '2081': ['Levator labii superioris', null],
  '2082': ['Levator labii superioris alaeque nasi muscle', null],
  '2083': ['Depressor labii inferioris muscle', null],
  '2084': ['Levator anguli oris', null],
  '2086': ['Buccinator muscle', null],
  '2087': ['Mentalis', null],
  '2089': ['Anterior auricular muscle', null],
  '2090': ['Superior auricular muscle', null],
  '2091': ['Posterior auricular muscle', null],
  '2102': ['Tensor tympani muscle', null],
  '2103': ['Stapedius muscle', null],
  '2106': ['Superficial part of masseter', null],
  '2107': ['Deep part of masseter', null],
  '2108': ['Temporal muscle', null],
  '2110': ['Superior head of lateral pterygoid muscle', null],
  '2111': ['Inferior head of lateral pterygoid muscle', null],
  '2113': ['Medial pterygoid muscle', null],
  '2117': ['Genioglossus', null],
  '2118': ['Hyoglossus', null],
  '2121': ['Styloglossus', null],
  '2128': ['Levator veli palatini', null],
  '2129': ['Tensor veli palatini muscle', null],
  '2130': ['Musculus uvulae', null],
  '2131': ['Palatoglossus muscle', null],
  '2132': ['Palatopharyngeus muscle', null],
  '2147': ['Platysma muscle', null],
  '2148': ['Longus colli muscle', null],
  '2149': ['Longus capitis muscle', null],
  '2150': ['Rectus capitis anterior muscle', null],
  '2151': ['Rectus capitis lateralis muscle', null],
  '2152': ['Scalenus anterior', null],
  '2153': ['Scalenus medius', null],
  '2154': ['Scalenus posterior', null],
  '2156': ['Sternocleidomastoid muscle', null],
  '2161': ['Anterior belly of digastric', null],
  '2162': ['Intermediate tendon of digastric muscle', null],
  '2163': ['Posterior belly of digastric', null],
  '2164': ['Stylohyoid muscle', null],
  '2165': ['Mylohyoid muscle', null],
  '2166': ['Geniohyoid muscle', null],
  '2168': ['Sternohyoid muscle', null],
  '2169': ['Omohyoid muscle', null],
  '2173': ['Sternothyroid muscle', null],
  '2174': ['Thyrohyoid muscle', null],
  '2179': ['Superior pharyngeal constrictor muscle', null],
  '2184': ['Middle pharyngeal constrictor muscle', null],
  '2187': ['Inferior pharyngeal constrictor muscle', null],
  '2190': ['Stylopharyngeus muscle', null],
  '2191': ['Salpingopharyngeus muscle', null],
  '2194': ['Straight part of cricothyroid muscle', null],
  '2195': ['Oblique part of cricothyroid', null],
  '2196': ['Posterior cricoarytenoid muscle', null],
  '2198': ['Lateral cricoarytenoid muscle', null],
  '2200': ['External part of thyro-arytenoid muscle', null],
  '2201': ['Thyro-epiglottic part of thyro-arytenoid muscle', null],
  '2202': ['Vocal muscle', null],
  '2204': ['Aryepiglottic part of oblique arytenoid muscle', null],
  '2205': ['Transverse arytenoid muscle', null],
  '2227': ['Descending part of trapezius', 'traps'],
  '2228': ['Transverse part of trapezius', 'traps'],
  '2229': ['Ascending part of trapezius', 'traps'],
  '2231': ['Latissimus dorsi muscle', 'lats'],
  '2232': ['Rhomboid major muscle', 'upper_back'],
  '2233': ['Rhomboid minor muscle', 'upper_back'],
  '2234': ['Levator scapulae muscle', 'traps'],
  '2235': ['Serratus posterior inferior muscle', 'lower_back'],
  '2236': ['Serratus posterior superior muscle', 'upper_back'],
  '2237': ['Anterior intertransversarii colli muscles', null],
  '2238': ['Lateral posterior intertransversarii colli muscles', null],
  '2239': ['Lateral intertransversarii lumborum muscles', null],
  '2240': ['Posterior parts of lateral intertransversarii lumborum muscles', null],
  '2241': ['Anterior parts of lateral intertransversarii lumborum muscles', null],
  '2249': ['Rectus capitis posterior major muscle', null],
  '2250': ['Rectus capitis posterior minor muscle', null],
  '2251': ['Obliquus capitis superior muscle', null],
  '2252': ['Obliquus capitis inferior muscle', null],
  '2258': ['Iliocostalis lumborum muscle', 'lower_back'],
  '2260': ['Iliocostalis thoracis muscle', 'lower_back'],
  '2261': ['Iliocostalis colli muscle', null],
  '2263': ['Longissimus thoracis', 'lower_back'],
  '2265': ['Longissimus colli muscle', null],
  '2266': ['Longissimus capitis muscle', null],
  '2268': ['Spinalis thoracis muscle', 'lower_back'],
  '2269': ['Spinalis colli muscle', null],
  '2270': ['Spinalis capitis muscle', null],
  '2273': ['Splenius capitis muscle', null],
  '2274': ['Splenius cervicis muscle', null],
  '2277': ['Multifidus lumborum muscle', 'lower_back'],
  '2278': ['Multifidus thoracis muscle', 'lower_back'],
  '2279': ['Multifidus colli muscle', null],
  '2281': ['Semispinalis thoracis', 'lower_back'],
  '2282': ['Semispinalis cervicis', null],
  '2283': ['Semispinalis capitis', null],
  '2284': ['Rotatores muscles', null],
  '2285': ['Lumbar rotator', 'lower_back'],
  '2289': ['Rotatores colli', null],
  '2291': ['Interspinales lumborum muscles', null],
  '2292': ['Interspinales thoracis muscles', null],
  '2293': ['Interspinales colli muscles', null],
  '2295': ['Medial intertransversarii lumborum muscles', null],
  '2302': ['Clavicular head of pectoralis major', 'chest'],
  '2303': ['Sternocostal head of pectoralis major muscle', 'chest'],
  '2304': ['Abdominal part of pectoralis major muscle', 'chest'],
  '2305': ['Pectoralis minor muscle', 'chest'],
  '2306': ['Subclavius muscle', null],
  '2307': ['Serratus anterior muscle', 'obliques'],
  '2309': ['Levatores longi costarum', null],
  '2310': ['Levatores breves costarum', null],
  '2311': ['External intercostal muscles', null],
  '2312': ['Internal intercostal muscle', null],
  '2313': ['Innermost intercostal muscle', null],
  '2314': ['Subcostalis muscle', null],
  '2315': ['Transversus thoracis muscle', null],
  '2327': ['Thoracic diaphragm', null],
  '2357': ['Rectus abdominis muscle', 'abs'],
  '2363': ['Pyramidalis muscle', 'abs'],
  '2364': ['Abdominal external oblique muscle', 'obliques'],
  '2373': ['Abdominal internal oblique muscle', 'obliques'],
  '2374': ['Cremaster muscle', null],
  '2375': ['Transversus abdominis muscle', 'abs'],
  '2382': ['Quadratus lumborum muscle', 'lower_back'],
  '2404': ['Iliococcygeus muscle', null],
  '2405': ['Pubococcygeus muscle', null],
  '2406': ['Pubo-analis muscle', null],
  '2412': ['Coccygeus muscle', null],
  '2416': ['Superficial transverse perineal muscle', null],
  '2417': ['Ischiocavernosus muscle', null],
  '2418': ['Bulbospongiosus muscle', null],
  '2420': ['Deep transverse perineal muscle', null],
  '2421': ['External sphincter muscle of male urethra', null],
  '2426': ['External anal sphincter', null],
  '2434': ['Tendinous arch of levator ani', null],
  '2453': ['Clavicular part of deltoid', 'shoulders'],
  '2454': ['Acromial part of deltoid', 'shoulders'],
  '2455': ['Scapular spinal part of deltoid muscle', 'shoulders'],
  '2457': ['Supraspinatus muscle', 'shoulders'],
  '2458': ['Infraspinatus muscle', 'shoulders'],
  '2459': ['Teres minor muscle', 'shoulders'],
  '2460': ['Subscapularis muscle', 'shoulders'],
  '2462': ['Teres major muscle', 'upper_back'],
  '2465': ['Long head of the biceps brachii', 'biceps'],
  '2466': ['Short head of the biceps brachii', 'biceps'],
  '2468': ['Coracobrachialis muscle', 'biceps'],
  '2469': ['Brachialis muscle', 'biceps'],
  '2472': ['Long head of triceps brachii', 'triceps'],
  '2473': ['Lateral head of triceps brachii', 'triceps'],
  '2474': ['Medial head of triceps brachii', 'triceps'],
  '2479': ['Superficial head of pronator teres', 'forearms'],
  '2480': ['Deep head of pronator teres', 'forearms'],
  '2481': ['Flexor carpi radialis muscle', 'forearms'],
  '2482': ['Palmaris longus muscle', 'forearms'],
  '2484': ['Humeral head of flexor carpi ulnaris', 'forearms'],
  '2485': ['Ulnar head of flexor carpi ulnaris', 'forearms'],
  '2487': ['Humero-ulnar head of flexor digitorum superficialis', 'forearms'],
  '2488': ['Radial head of flexor digitorum superficialis', 'forearms'],
  '2491': ['Flexor digitorum profundus muscle', 'forearms'],
  '2492': ['Flexor pollicis longus muscle', 'forearms'],
  '2493': ['Pronator quadratus muscle', 'forearms'],
  '2496': ['Brachioradialis', 'forearms'],
  '2497': ['Extensor carpi radialis longus muscle', 'forearms'],
  '2499': ['Extensor carpi radialis brevis muscle', 'forearms'],
  '2500': ['Extensor digitorum muscle of hand', 'forearms'],
  '2506': ['Extensor digiti minimi muscle', 'forearms'],
  '2508': ['Humeral head of extensor carpi ulnaris', 'forearms'],
  '2509': ['Ulnar head of extensor carpi ulnaris', 'forearms'],
  '2510': ['Anconeus muscle', 'triceps'],
  '2512': ['Supinator muscle', 'forearms'],
  '2515': ['Extensor indicis muscle', 'forearms'],
  '2516': ['Extensor pollicis longus muscle', 'forearms'],
  '2517': ['Abductor pollicis longus muscle', 'forearms'],
  '2518': ['Extensor pollicis brevis muscle', 'forearms'],
  '2520': ['Palmaris brevis muscle', null],
  '2521': ['Abductor pollicis brevis muscle', null],
  '2523': ['Superficial head of flexor pollicis brevis', null],
  '2524': ['Deep head of flexor pollicis brevis', null],
  '2525': ['Opponens pollicis muscle', null],
  '2527': ['Oblique head of adductor pollicis', null],
  '2528': ['Transverse head of adductor pollicis', null],
  '2529': ['Abductor digiti minimi muscle of hand', null],
  '2530': ['Flexor digiti minimi brevis muscle of hand', null],
  '2531': ['Opponens digiti minimi muscle of hand', null],
  '2534': ['Palmar interossei muscles', null],
  '2594': ['Iliacus muscle', null],
  '2595': ['Psoas major muscle', null],
  '2598': ['Gluteus maximus muscle', 'glutes'],
  '2599': ['Gluteus medius muscle', 'glutes'],
  '2600': ['Gluteus minimus muscle', 'glutes'],
  '2602': ['Tensor fasciae latae muscle', 'glutes'],
  '2604': ['Piriformis muscle', 'glutes'],
  '2605': ['Obturator internus muscle', null],
  '2606': ['Superior gemellus muscle', null],
  '2607': ['Inferior gemellus muscle', null],
  '2608': ['Quadratus femoris muscle', null],
  '2610': ['Sartorius muscle', 'quads'],
  '2614': ['Rectus femoris muscle', 'quads'],
  '2618': ['Vastus lateralis muscle', 'quads'],
  '2619': ['Vastus intermedius muscle', 'quads'],
  '2620': ['Vastus medialis', 'quads'],
  '2627': ['Pectineus muscle', 'adductors'],
  '2628': ['Adductor longus muscle', 'adductors'],
  '2629': ['Adductor brevis muscle', 'adductors'],
  '2630': ['Adductor magnus muscle', 'adductors'],
  '2632': ['Adductor minimus muscle', 'adductors'],
  '2635': ['Gracilis muscle', 'adductors'],
  '2636': ['Obturator externus muscle', null],
  '2639': ['Long head of biceps femoris muscle', 'hamstrings'],
  '2640': ['Short head of biceps femoris muscle', 'hamstrings'],
  '2641': ['Semitendinosus muscle', 'hamstrings'],
  '2642': ['Semimembranosus muscle', 'hamstrings'],
  '2644': ['Tibialis anterior muscle', null],
  '2645': ['Extensor digitorum longus muscle', null],
  '2649': ['Fibularis tertius', null],
  '2650': ['Extensor hallucis longus muscle', null],
  '2652': ['Fibularis longus', null],
  '2653': ['Fibularis brevis muscle', null],
  '2658': ['Lateral head of gastrocnemius muscle', 'calves'],
  '2659': ['Medial head of gastrocnemius muscle', 'calves'],
  '2660': ['Soleus muscle', 'calves'],
  '2662': ['Achilles tendon', null],
  '2663': ['Plantaris muscle', 'calves'],
  '2665': ['Popliteus muscle', null],
  '2666': ['Tibialis posterior muscle', null],
  '2667': ['Flexor digitorum longus muscle', null],
  '2668': ['Flexor hallucis longus muscle', null],
  '2670': ['Extensor hallucis brevis muscle', null],
  '2671': ['Extensor digitorum brevis muscle', null],
  '2672': ['Abductor hallucis muscle', null],
  '2674': ['Medial head of flexor hallucis brevis', null],
  '2675': ['Lateral head of flexor hallucis brevis', null],
  '2677': ['Oblique head of adductor hallucis', null],
  '2678': ['Transverse head of adductor hallucis', null],
  '2679': ['Abductor digiti minimi muscle of foot', null],
  '2681': ['Opponens digiti minimi of foot', null],
  '2682': ['Flexor digiti minimi brevis muscle of foot', null],
  '2683': ['Flexor digitorum brevis muscle', null],
  '2684': ['Quadratus plantae muscle', null],
  '2685': ['Lumbricals of the foot', null],
  '2690': ['Iliotibial tract', null],
  'x-first-dorsal-interosseous-muscle-of-foot': ['First dorsal interosseous muscle of foot', null],
  'x-first-dorsal-interosseous-muscle-of-hand': ['First dorsal interosseous muscle of hand', null],
  'x-first-lumbrical-muscle-of-hand': ['First lumbrical muscle of hand', null],
  'x-first-plantar-interosseous-muscle': ['First plantar interosseous muscle', null],
  'x-fourth-dorsal-interosseous-muscle-of-foot': ['Fourth dorsal interosseous muscle of foot', null],
  'x-fourth-dorsal-interosseous-muscle-of-hand': ['Fourth dorsal interosseous muscle of hand', null],
  'x-fourth-lumbrical-muscle-of-hand': ['Fourth lumbrical muscle of hand', null],
  'x-second-dorsal-interosseous-muscle-of-foot': ['Second dorsal interosseous muscle of foot', null],
  'x-second-dorsal-interosseous-muscle-of-hand': ['Second dorsal interosseous muscle of hand', null],
  'x-second-lumbrical-muscle-of-hand': ['Second lumbrical muscle of hand', null],
  'x-second-plantar-interosseous-muscle': ['Second plantar interosseous muscle', null],
  'x-third-dorsal-interosseous-muscle-of-foot': ['Third dorsal interosseous muscle of foot', null],
  'x-third-dorsal-interosseous-muscle-of-hand': ['Third dorsal interosseous muscle of hand', null],
  'x-third-lumbrical-muscle-of-hand': ['Third lumbrical muscle of hand', null],
  'x-third-plantar-interosseous-muscle': ['Third plantar interosseous muscle', null],
}

/**
 * 'ta2-2303.l' → { id: '2303', side: 'l' }. three.js strips the '.' when it
 * loads node names ('ta2-2303l'), so the dot is optional.
 */
export function parseNodeName(name: string) {
  const m = /^ta2-(.+?)\.?([lrm])$/.exec(name)
  return m ? { id: m[1], side: m[2] as 'l' | 'r' | 'm' } : null
}

export function muscleInfo(nodeName: string) {
  const p = parseNodeName(nodeName)
  if (!p) return null
  const entry = TA2_MUSCLES[p.id]
  if (!entry) return null
  const side = p.side === 'l' ? 'Left' : p.side === 'r' ? 'Right' : null
  return { name: entry[0], group: entry[1], side }
}
